services:
  traefik:
    image: traefik:v3.1
    command:
      - "--api.insecure=true"
      - "--api=true"
      - "--api.dashboard=true"
      - "--log.level=INFO"
      - "--entrypoints.web.address=:80"

      - "--providers.file.filename=/etc/traefik/config/traefik.yml"
      - "--providers.file.watch=true"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./config:/etc/traefik/config/
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge
