services:
  backup-error-webserver:
    image: backup-error-webserver
    build: .
    ports:
      - "80:80"
    volumes:
      - ./test-traefik-failover/content:/content
    environment:
      - CONTENT_HTML_FILE="/content/content.html"